export type StorefrontSeedCategory = {
  code: string;
  name: string;
  description: string;
  type:
    | "ACCESORIO"
    | "JUGUETE_SEXUAL"
    | "LUBRICANTE"
    | "PRESERVATIVO"
    | "COSMETICO"
    | "LENCERIA"
    | "BDSM"
    | "HIGIENE"
    | "OTRO";
  imageUrl: string;
  basePrice: number;
  priceStep: number;
  requiresSanitary: boolean;
  handlesLots: boolean;
  handlesExpiry: boolean;
  storageMin?: number;
  storageMax?: number;
  items: string[];
};

export const STOREFRONT_PRICE_START = "2026-01-01";

export const STOREFRONT_PRODUCT_IMAGE_BY_SKU: Record<string, string> = {
  "PRODUCTOSMAS-001": "/assets/store/products/productosmas-001.webp",
  "PRODUCTOSMAS-002": "/assets/store/products/productosmas-002.webp",
  "PRODUCTOSMAS-003": "/assets/store/products/productosmas-003.webp",
  "PRODUCTOSMAS-004": "/assets/store/products/productosmas-004.webp",
  "PRODUCTOSMAS-005": "/assets/store/products/productosmas-005.webp",
  "PRODUCTOSMAS-006": "/assets/store/products/productosmas-006.webp",
  "PRODUCTOSFEM-001": "/assets/store/products/productosfem-001.webp",
  "PRODUCTOSFEM-002": "/assets/store/products/productosfem-002.webp",
  "PRODUCTOSFEM-003": "/assets/store/products/productosfem-003.webp",
  "PRODUCTOSFEM-004": "/assets/store/products/productosfem-004.webp",
  "PRODUCTOSFEM-005": "/assets/store/products/productosfem-005.webp",
  "HIGIENEINTIM-001": "/assets/store/products/higieneintim-001.webp",
  "HIGIENEINTIM-002": "/assets/store/products/higieneintim-002.webp",
  "HIGIENEINTIM-003": "/assets/store/products/higieneintim-003.webp",
  "HIGIENEINTIM-004": "/assets/store/products/higieneintim-004.webp",
  "HIGIENEINTIM-005": "/assets/store/products/higieneintim-005.webp",
  "KITSCOMBOS-001": "/assets/store/products/kitscombos-001.webp",
  "KITSCOMBOS-002": "/assets/store/products/kitscombos-002.webp",
  "KITSCOMBOS-003": "/assets/store/products/kitscombos-003.webp",
  "KITSCOMBOS-004": "/assets/store/products/kitscombos-004.webp",
  "ACCESORIOSAL-001": "/assets/store/products/accesoriosal-001.webp",
  "ACCESORIOSAL-002": "/assets/store/products/accesoriosal-002.webp",
  "ACCESORIOSAL-003": "/assets/store/products/accesoriosal-003.webp",
  "ACCESORIOSAL-004": "/assets/store/products/accesoriosal-004.webp",
  "ACCESORIOSAL-005": "/assets/store/products/accesoriosal-005.webp",
  "COSMETICAERO-001": "/assets/store/products/cosmeticaero-001.webp",
  "COSMETICAERO-002": "/assets/store/products/cosmeticaero-002.webp",
  "COSMETICAERO-003": "/assets/store/products/cosmeticaero-003.webp",
  "COSMETICAERO-004": "/assets/store/products/cosmeticaero-004.webp",
  "COSMETICAERO-005": "/assets/store/products/cosmeticaero-005.webp",
  "SMARTTOYS-001": "/assets/store/products/smarttoys-001.webp",
  "SMARTTOYS-002": "/assets/store/products/smarttoys-002.webp",
  "SMARTTOYS-003": "/assets/store/products/smarttoys-003.webp",
  "SMARTTOYS-004": "/assets/store/products/smarttoys-004.webp",
};

export const STOREFRONT_SEED_CATEGORIES: StorefrontSeedCategory[] = [
  {
    code: "JUGUETES-SEXUALES",
    name: "Juguetes sexuales",
    description: "Vibracion, fantasia y placer premium para explorar sin limites.",
    type: "JUGUETE_SEXUAL",
    imageUrl: "/assets/store/catalog/neon-desire.svg",
    basePrice: 69900,
    priceStep: 12000,
    requiresSanitary: false,
    handlesLots: false,
    handlesExpiry: false,
    items: [
      "Vibradores",
      "Bullet",
      "Rabbit",
      "Punto G",
      "Varita (wand)",
      "Succionadores tipo Satisfyer",
      "Dildos realistas",
      "Dildos fantasy",
      "Dildos dobles",
      "Plug anal",
      "Bolas chinas / Kegel",
      "Masturbadores masculinos",
      "Masturbadores tipo huevo",
      "Masturbadores automaticos",
      "Anillos para pene",
      "Bombas de vacio",
      "Juguetes para pareja",
      "Huevos vibradores con control remoto",
    ],
  },
  {
    code: "ESTIMULACION-ANAL",
    name: "Estimulacion anal",
    description: "Exploracion gradual, control y sensaciones intensas con total comodidad.",
    type: "JUGUETE_SEXUAL",
    imageUrl: "/assets/store/catalog/obsidian-glow.svg",
    basePrice: 54900,
    priceStep: 9000,
    requiresSanitary: false,
    handlesLots: false,
    handlesExpiry: false,
    items: [
      "Plug anal de silicona",
      "Plug anal de metal",
      "Plug anal con joya",
      "Bolas anales",
      "Vibradores anales",
      "Kits de iniciacion anal",
      "Duchas anales",
      "Dilatadores",
    ],
  },
  {
    code: "LUBRICANTES-ESTIMULANTES",
    name: "Lubricantes y estimulantes",
    description: "Texturas y formulas para comodidad, deslizamiento y sensaciones memorables.",
    type: "LUBRICANTE",
    imageUrl: "/assets/store/catalog/liquid-heat.svg",
    basePrice: 32900,
    priceStep: 7000,
    requiresSanitary: true,
    handlesLots: true,
    handlesExpiry: true,
    storageMin: 15,
    storageMax: 28,
    items: [
      "Lubricantes base agua",
      "Lubricantes base silicona",
      "Lubricantes base aceite",
      "Lubricantes anales",
      "Lubricantes saborizados",
      "Gel estimulante femenino",
      "Gel estimulante masculino",
      "Retardantes",
      "Excitantes termicos (frio/calor)",
    ],
  },
  {
    code: "PRESERVATIVOS-PROTECCION",
    name: "Preservativos y proteccion",
    description: "Proteccion erotica con opciones para sensacion, rendimiento y variedad.",
    type: "PRESERVATIVO",
    imageUrl: "/assets/store/catalog/protection-spark.svg",
    basePrice: 17900,
    priceStep: 5000,
    requiresSanitary: true,
    handlesLots: true,
    handlesExpiry: true,
    storageMin: 15,
    storageMax: 28,
    items: [
      "Condones clasicos",
      "Ultra delgados",
      "Extra resistentes",
      "Retardantes",
      "Texturizados",
      "Saborizados",
      "Condones femeninos",
      "Packs y cajas",
    ],
  },
  {
    code: "LENCERIA-EROTICA",
    name: "Lenceria erotica",
    description: "Siluetas, transparencias y looks que despiertan el deseo a primera vista.",
    type: "LENCERIA",
    imageUrl: "/assets/store/catalog/crimson-lace.svg",
    basePrice: 79900,
    priceStep: 15000,
    requiresSanitary: false,
    handlesLots: false,
    handlesExpiry: false,
    items: [
      "Bodys",
      "Babydolls",
      "Conjuntos (brasier + panty)",
      "Corsets",
      "Medias",
      "Ligueros",
      "Lenceria masculina",
      "Disfraces eroticos",
    ],
  },
  {
    code: "BDSM-FETICHE",
    name: "BDSM y fetiche",
    description: "Dominacion, juego de roles y accesorios para experiencias consensuadas mas intensas.",
    type: "BDSM",
    imageUrl: "/assets/store/catalog/velvet-command.svg",
    basePrice: 59900,
    priceStep: 11000,
    requiresSanitary: false,
    handlesLots: false,
    handlesExpiry: false,
    items: [
      "Esposas de metal",
      "Esposas de cuero",
      "Esposas de tela",
      "Latigos",
      "Fustas",
      "Arneses",
      "Collares y correas",
      "Mordazas",
      "Vendas",
      "Kits BDSM",
      "Jaulas de castidad",
    ],
  },
  {
    code: "PRODUCTOS-PAREJA",
    name: "Productos para pareja",
    description: "Juegos, vibracion compartida y rituales sensuales para dos.",
    type: "JUGUETE_SEXUAL",
    imageUrl: "/assets/store/catalog/couple-pulse.svg",
    basePrice: 45900,
    priceStep: 10000,
    requiresSanitary: false,
    handlesLots: false,
    handlesExpiry: false,
    items: [
      "Juegos eroticos (dados, cartas)",
      "Kits para pareja",
      "Vibradores para pareja",
      "Aceites de masaje",
      "Velas eroticas",
    ],
  },
  {
    code: "PRODUCTOS-MASCULINOS",
    name: "Productos masculinos",
    description: "Estimulo, rendimiento y accesorios pensados para el placer masculino.",
    type: "JUGUETE_SEXUAL",
    imageUrl: "/assets/store/catalog/midnight-magnet.svg",
    basePrice: 44900,
    priceStep: 12000,
    requiresSanitary: false,
    handlesLots: false,
    handlesExpiry: false,
    items: [
      "Masturbadores",
      "Bombas de vacio",
      "Extensores / mangas",
      "Anillos para pene",
      "Retardantes",
      "Cremas potenciadoras",
    ],
  },
  {
    code: "PRODUCTOS-FEMENINOS",
    name: "Productos femeninos",
    description: "Placer focalizado y bienestar intimo con tecnologia y suavidad.",
    type: "JUGUETE_SEXUAL",
    imageUrl: "/assets/store/catalog/rose-vibration.svg",
    basePrice: 52900,
    priceStep: 11000,
    requiresSanitary: false,
    handlesLots: false,
    handlesExpiry: false,
    items: [
      "Vibradores punto G",
      "Succionadores",
      "Bolas Kegel",
      "Lubricantes femeninos",
      "Estimulantes clitorales",
    ],
  },
  {
    code: "HIGIENE-INTIMA",
    name: "Higiene intima",
    description: "Limpieza, cuidado y confianza para cuerpo y accesorios eroticos.",
    type: "HIGIENE",
    imageUrl: "/assets/store/catalog/pure-touch.svg",
    basePrice: 24900,
    priceStep: 6000,
    requiresSanitary: true,
    handlesLots: true,
    handlesExpiry: true,
    storageMin: 15,
    storageMax: 28,
    items: [
      "Limpiadores de juguetes",
      "Jabones intimos",
      "Toallitas intimas",
      "Duchas vaginales",
      "Duchas anales",
    ],
  },
  {
    code: "KITS-COMBOS",
    name: "Kits y combos",
    description: "Paquetes listos para regalar, empezar o subir el juego de nivel.",
    type: "OTRO",
    imageUrl: "/assets/store/catalog/boxed-desire.svg",
    basePrice: 89900,
    priceStep: 17000,
    requiresSanitary: false,
    handlesLots: false,
    handlesExpiry: false,
    items: [
      "Kits para principiantes",
      "Kits BDSM",
      "Kits para pareja",
      "Cajas sorpresa eroticas",
    ],
  },
  {
    code: "ACCESORIOS-ALMACENAMIENTO",
    name: "Accesorios y almacenamiento",
    description: "Estuches, organizacion y energia para que todo este listo y discreto.",
    type: "ACCESORIO",
    imageUrl: "/assets/store/catalog/noir-storage.svg",
    basePrice: 19900,
    priceStep: 8000,
    requiresSanitary: false,
    handlesLots: false,
    handlesExpiry: false,
    items: [
      "Estuches",
      "Bolsas discretas",
      "Cargadores",
      "Baterias",
      "Organizadores",
    ],
  },
  {
    code: "SMART-TOYS",
    name: "Tecnologia (Smart Toys)",
    description: "Placer conectado para parejas a distancia y experiencias premium.",
    type: "JUGUETE_SEXUAL",
    imageUrl: "/assets/store/catalog/electric-desire.svg",
    basePrice: 129900,
    priceStep: 22000,
    requiresSanitary: false,
    handlesLots: false,
    handlesExpiry: false,
    items: [
      "Juguetes con app",
      "Vibradores bluetooth",
      "Control remoto a distancia",
      "Dispositivos inteligentes conectados",
    ],
  },
  {
    code: "COSMETICA-EROTICA",
    name: "Cosmetica erotica",
    description: "Aromas, calor y sensaciones para convertir la compra en ritual.",
    type: "COSMETICO",
    imageUrl: "/assets/store/catalog/amber-glow.svg",
    basePrice: 28900,
    priceStep: 9000,
    requiresSanitary: true,
    handlesLots: true,
    handlesExpiry: true,
    storageMin: 15,
    storageMax: 28,
    items: [
      "Aceites de masaje",
      "Perfumes con feromonas",
      "Cremas estimulantes",
      "Velas de masaje",
      "Gel corporal saborizado",
    ],
  },
];
