import { EntityConfig } from '../models/app.models';

export const ENTITY_REGISTRY: Record<string, EntityConfig> = {
  'security/users': {
    key: 'users',
    domain: 'security',
    title: 'Usuarios',
    subtitle: 'Administración de cuentas, credenciales y acceso operativo.',
    endpoint: '/security/users',
    idKey: 'id_usuario',
    permission: 'security.manage',
    badge: 'Seguridad',
    createMode: 'guided',
    columns: [
      { key: 'nombre_usuario', label: 'Usuario' },
      { key: 'correo_electronico', label: 'Correo' },
      { key: 'nombres', label: 'Nombres' },
      { key: 'apellidos', label: 'Apellidos' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'nombres', label: 'Nombres', type: 'text', required: true },
      { key: 'apellidos', label: 'Apellidos', type: 'text', required: true },
      { key: 'correo_electronico', label: 'Correo', type: 'email', required: true },
      { key: 'telefono', label: 'Teléfono', type: 'text' },
      { key: 'nombre_usuario', label: 'Usuario', type: 'text', required: true },
      { key: 'password', label: 'Contraseña inicial', type: 'password', required: true },
      {
        key: 'requiere_cambio_clave',
        label: 'Exigir cambio de clave',
        type: 'checkbox',
        defaultValue: true,
      },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'security/roles': {
    key: 'roles',
    domain: 'security',
    title: 'Roles',
    subtitle: 'Perfiles funcionales y agrupación de permisos.',
    endpoint: '/security/roles',
    idKey: 'id_rol',
    permission: 'security.manage',
    badge: 'Seguridad',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'descripcion', label: 'Descripción' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'codigo', label: 'Código', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'descripcion', label: 'Descripción', type: 'textarea', rows: 3 },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'security/permissions': {
    key: 'permissions',
    domain: 'security',
    title: 'Permisos',
    subtitle: 'Permisos funcionales vinculados a módulos y acciones.',
    endpoint: '/security/permissions',
    idKey: 'id_permiso',
    permission: 'security.manage',
    badge: 'Seguridad',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'modulo', label: 'Módulo' },
      { key: 'accion', label: 'Acción' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'modulo', label: 'Módulo', type: 'text', required: true },
      { key: 'codigo', label: 'Código', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'descripcion', label: 'Descripción', type: 'textarea', rows: 3 },
      { key: 'accion', label: 'Acción', type: 'text', required: true },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/categories': {
    key: 'categories',
    domain: 'masters',
    title: 'Categorías',
    subtitle: 'Jerarquía comercial y regulatoria de productos.',
    endpoint: '/masters/categories',
    idKey: 'id_categoria_producto',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'nivel', label: 'Nivel' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      {
        key: 'codigo',
        label: 'Código',
        type: 'text',
        required: true,
        section: 'Identidad',
        hint: 'Usa un código corto y estable para la categoría.',
      },
      {
        key: 'nombre',
        label: 'Nombre',
        type: 'text',
        required: true,
        section: 'Identidad',
      },
      {
        key: 'descripcion',
        label: 'Descripción',
        type: 'textarea',
        rows: 3,
        section: 'Identidad',
        columnSpan: 'full',
      },
      {
        key: 'id_categoria_padre',
        label: 'Categoría padre',
        type: 'select',
        section: 'Jerarquia',
        hint: 'Déjalo vacío si es una categoría principal.',
        optionConfig: {
          endpoint: '/masters/categories',
          labelKey: 'nombre',
          valueKey: 'id_categoria_producto',
          query: { activo: true, limit: 200, page: 1 },
        },
      },
      {
        key: 'nivel',
        label: 'Nivel',
        type: 'number',
        defaultValue: 1,
        section: 'Jerarquia',
      },
      {
        key: 'permite_venta_menores',
        label: 'Permite venta a menores',
        type: 'checkbox',
        section: 'Reglas',
      },
      {
        key: 'activo',
        label: 'Activo',
        type: 'checkbox',
        defaultValue: true,
        section: 'Reglas',
      },
    ],
  },
  'masters/brands': {
    key: 'brands',
    domain: 'masters',
    title: 'Marcas',
    subtitle: 'Fabricantes y marcas comerciales.',
    endpoint: '/masters/brands',
    idKey: 'id_marca',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'descripcion', label: 'Descripción' },
      { key: 'activa', label: 'Activa', type: 'boolean' },
    ],
    formFields: [
      { key: 'codigo', label: 'Código', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'descripcion', label: 'Descripción', type: 'textarea', rows: 3 },
      { key: 'activa', label: 'Activa', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/products': {
    key: 'products',
    domain: 'masters',
    title: 'Productos',
    subtitle: 'Ficha maestra de referencias, control sanitario y reglas de stock.',
    endpoint: '/masters/products',
    idKey: 'id_producto',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'sku', label: 'SKU' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'tipo_producto', label: 'Tipo' },
      { key: 'stock_minimo', label: 'Stock mínimo' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      {
        key: 'sku',
        label: 'SKU',
        type: 'text',
        required: true,
        section: 'Identidad comercial',
        hint: 'Identificador único para compras, stock y ventas.',
      },
      {
        key: 'codigo_barras',
        label: 'Código de barras',
        type: 'text',
        section: 'Identidad comercial',
      },
      {
        key: 'nombre',
        label: 'Nombre',
        type: 'text',
        required: true,
        section: 'Identidad comercial',
      },
      {
        key: 'nombre_corto',
        label: 'Nombre corto',
        type: 'text',
        section: 'Identidad comercial',
      },
      {
        key: 'descripcion',
        label: 'Descripción',
        type: 'textarea',
        rows: 4,
        section: 'Identidad comercial',
        columnSpan: 'full',
      },
      {
        key: 'url_imagen_principal',
        label: 'Imagen principal',
        type: 'file',
        accept: 'image/*',
        uploadEndpoint: '/masters/products/upload-image',
        hint: 'Selecciona una imagen y el sistema la sube automaticamente.',
        section: 'Identidad comercial',
        columnSpan: 'full',
      },
      {
        key: 'id_categoria_producto',
        label: 'Categoría',
        type: 'select',
        required: true,
        section: 'Clasificacion',
        hint: 'Ubica el producto dentro de la familia correcta para storefront y reportes.',
        optionConfig: {
          endpoint: '/masters/categories',
          labelKey: 'nombre',
          valueKey: 'id_categoria_producto',
          query: { activo: true, limit: 200, page: 1 },
        },
      },
      {
        key: 'id_marca',
        label: 'Marca',
        type: 'select',
        section: 'Clasificacion',
        optionConfig: {
          endpoint: '/masters/brands',
          labelKey: 'nombre',
          valueKey: 'id_marca',
          query: { activa: true, limit: 200, page: 1 },
        },
      },
      {
        key: 'id_unidad_medida_base',
        label: 'Unidad base',
        type: 'select',
        required: true,
        section: 'Clasificacion',
        hint: 'Unidad principal con la que se controla el inventario.',
        optionConfig: {
          endpoint: '/masters/units',
          labelKey: 'nombre',
          valueKey: 'id_unidad_medida',
          query: { activo: true, limit: 200, page: 1 },
        },
      },
      {
        key: 'tipo_producto',
        label: 'Tipo de producto',
        type: 'text',
        required: true,
        defaultValue: 'JUGUETE_SEXUAL',
        section: 'Clasificacion',
      },
      { key: 'subtipo_producto', label: 'Subtipo', type: 'text', section: 'Clasificacion' },
      { key: 'stock_minimo', label: 'Stock mínimo', type: 'number', section: 'Operacion y stock' },
      { key: 'stock_maximo', label: 'Stock máximo', type: 'number', section: 'Operacion y stock' },
      {
        key: 'punto_reorden',
        label: 'Punto de reorden',
        type: 'number',
        section: 'Operacion y stock',
      },
      {
        key: 'activo',
        label: 'Activo',
        type: 'checkbox',
        defaultValue: true,
        section: 'Reglas y control',
      },
      {
        key: 'es_inventariable',
        label: 'Inventariable',
        type: 'checkbox',
        defaultValue: true,
        section: 'Reglas y control',
      },
      { key: 'maneja_lotes', label: 'Maneja lotes', type: 'checkbox', section: 'Reglas y control' },
      {
        key: 'maneja_vencimiento',
        label: 'Maneja vencimiento',
        type: 'checkbox',
        section: 'Reglas y control',
      },
      {
        key: 'requiere_registro_sanitario',
        label: 'Requiere registro sanitario',
        type: 'checkbox',
        section: 'Reglas y control',
      },
      {
        key: 'requiere_control_mayoria_edad',
        label: 'Control mayoría de edad',
        type: 'checkbox',
        section: 'Reglas y control',
      },
      {
        key: 'observaciones',
        label: 'Observaciones',
        type: 'textarea',
        rows: 3,
        section: 'Notas',
        columnSpan: 'full',
      },
    ],
  },
  'masters/third-parties': {
    key: 'third-parties',
    domain: 'masters',
    title: 'Terceros',
    subtitle: 'Proveedores, clientes, fabricantes y demás contrapartes.',
    endpoint: '/masters/third-parties',
    idKey: 'id_tercero',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'tipo_tercero', label: 'Tipo' },
      { key: 'numero_documento', label: 'Documento' },
      { key: 'razon_social', label: 'Razón social' },
      { key: 'correo_electronico', label: 'Correo' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'tipo_tercero', label: 'Tipo de tercero', type: 'text', required: true },
      { key: 'tipo_persona', label: 'Tipo de persona', type: 'text', required: true },
      { key: 'numero_documento', label: 'Documento', type: 'text', required: true },
      { key: 'razon_social', label: 'Razón social', type: 'text' },
      { key: 'nombres', label: 'Nombres', type: 'text' },
      { key: 'apellidos', label: 'Apellidos', type: 'text' },
      { key: 'nombre_comercial', label: 'Nombre comercial', type: 'text' },
      { key: 'correo_electronico', label: 'Correo', type: 'email' },
      { key: 'telefono_principal', label: 'Teléfono', type: 'text' },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/countries': {
    key: 'countries',
    domain: 'masters',
    title: 'Paises',
    subtitle: 'Catalogo base de paises para terceros, sedes y direcciones.',
    endpoint: '/masters/countries',
    idKey: 'id_pais',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'codigo_iso2', label: 'ISO2' },
      { key: 'codigo_iso3', label: 'ISO3' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'codigo_iso2', label: 'Codigo ISO2', type: 'text', required: true },
      { key: 'codigo_iso3', label: 'Codigo ISO3', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/departments': {
    key: 'departments',
    domain: 'masters',
    title: 'Departamentos',
    subtitle: 'Division territorial de segundo nivel para direcciones y cobertura.',
    endpoint: '/masters/departments',
    idKey: 'id_departamento',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'id_pais', label: 'Id pais' },
      { key: 'codigo', label: 'Codigo' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'id_pais', label: 'Id pais', type: 'text', required: true },
      { key: 'codigo', label: 'Codigo', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/cities': {
    key: 'cities',
    domain: 'masters',
    title: 'Ciudades',
    subtitle: 'Catalogo de ciudades ligado a departamentos y terceros.',
    endpoint: '/masters/cities',
    idKey: 'id_ciudad',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'id_departamento', label: 'Id departamento' },
      { key: 'codigo', label: 'Codigo' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'id_departamento', label: 'Id departamento', type: 'text', required: true },
      { key: 'codigo', label: 'Codigo', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/units': {
    key: 'units',
    domain: 'masters',
    title: 'Unidades',
    subtitle: 'Unidades base y comerciales para compra, venta e inventario.',
    endpoint: '/masters/units',
    idKey: 'id_unidad_medida',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Codigo' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'descripcion', label: 'Descripcion' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'codigo', label: 'Codigo', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'descripcion', label: 'Descripcion', type: 'textarea', rows: 3 },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/currencies': {
    key: 'currencies',
    domain: 'masters',
    title: 'Monedas',
    subtitle: 'Monedas habilitadas para listas de precio, compras y ventas.',
    endpoint: '/masters/currencies',
    idKey: 'id_moneda',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Codigo' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'simbolo', label: 'Simbolo' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'codigo', label: 'Codigo', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'simbolo', label: 'Simbolo', type: 'text' },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/document-types': {
    key: 'document-types',
    domain: 'masters',
    title: 'Tipos de documento',
    subtitle: 'Identificacion para personas naturales y juridicas.',
    endpoint: '/masters/document-types',
    idKey: 'id_tipo_documento_identidad',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Codigo' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'aplica_persona_natural', label: 'Natural', type: 'boolean' },
      { key: 'aplica_persona_juridica', label: 'Juridica', type: 'boolean' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'codigo', label: 'Codigo', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'aplica_persona_natural', label: 'Aplica persona natural', type: 'checkbox', defaultValue: true },
      { key: 'aplica_persona_juridica', label: 'Aplica persona juridica', type: 'checkbox' },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/tax-types': {
    key: 'tax-types',
    domain: 'masters',
    title: 'Tipos de impuesto',
    subtitle: 'Catalogo tributario base para productos y documentos.',
    endpoint: '/masters/tax-types',
    idKey: 'id_tipo_impuesto',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Codigo' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'descripcion', label: 'Descripcion' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'codigo', label: 'Codigo', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'descripcion', label: 'Descripcion', type: 'textarea', rows: 3 },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/tax-rates': {
    key: 'tax-rates',
    domain: 'masters',
    title: 'Tasas de impuesto',
    subtitle: 'Porcentajes y vigencias tributarias por tipo.',
    endpoint: '/masters/tax-rates',
    idKey: 'id_tasa_impuesto',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'id_tipo_impuesto', label: 'Id tipo impuesto' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'porcentaje', label: 'Porcentaje' },
      { key: 'fecha_inicio_vigencia', label: 'Inicio', type: 'date' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'id_tipo_impuesto', label: 'Id tipo impuesto', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'porcentaje', label: 'Porcentaje', type: 'number', required: true },
      { key: 'fecha_inicio_vigencia', label: 'Inicio vigencia', type: 'date', required: true },
      { key: 'fecha_fin_vigencia', label: 'Fin vigencia', type: 'date' },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/general-states': {
    key: 'general-states',
    domain: 'masters',
    title: 'Estados generales',
    subtitle: 'Estados parametrizables por modulo y flujo.',
    endpoint: '/masters/general-states',
    idKey: 'id_estado_general',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'modulo', label: 'Modulo' },
      { key: 'codigo', label: 'Codigo' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'orden_visual', label: 'Orden' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'modulo', label: 'Modulo', type: 'text', required: true },
      { key: 'codigo', label: 'Codigo', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'descripcion', label: 'Descripcion', type: 'textarea', rows: 3 },
      { key: 'orden_visual', label: 'Orden visual', type: 'number', defaultValue: 1 },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/third-party-addresses': {
    key: 'third-party-addresses',
    domain: 'masters',
    title: 'Direcciones de terceros',
    subtitle: 'Direcciones operativas, fiscales y de entrega ligadas a terceros.',
    endpoint: '/masters/third-party-addresses',
    idKey: 'id_direccion_tercero',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'id_tercero', label: 'Id tercero' },
      { key: 'tipo_direccion', label: 'Tipo direccion' },
      { key: 'direccion_linea_1', label: 'Direccion principal' },
      { key: 'codigo_postal', label: 'Codigo postal' },
      { key: 'es_principal', label: 'Principal', type: 'boolean' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'id_tercero', label: 'Id tercero', type: 'text', required: true },
      { key: 'id_pais', label: 'Id pais', type: 'text', required: true },
      { key: 'id_departamento', label: 'Id departamento', type: 'text', required: true },
      { key: 'id_ciudad', label: 'Id ciudad', type: 'text', required: true },
      { key: 'direccion_linea_1', label: 'Direccion linea 1', type: 'textarea', rows: 2, required: true },
      { key: 'direccion_linea_2', label: 'Direccion linea 2', type: 'textarea', rows: 2 },
      { key: 'codigo_postal', label: 'Codigo postal', type: 'text' },
      { key: 'tipo_direccion', label: 'Tipo direccion', type: 'text', required: true },
      { key: 'latitud', label: 'Latitud', type: 'number' },
      { key: 'longitud', label: 'Longitud', type: 'number' },
      { key: 'es_principal', label: 'Es principal', type: 'checkbox' },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/third-party-bank-accounts': {
    key: 'third-party-bank-accounts',
    domain: 'masters',
    title: 'Cuentas bancarias de terceros',
    subtitle: 'Cuentas de recaudo y pago asociadas a terceros.',
    endpoint: '/masters/third-party-bank-accounts',
    idKey: 'id_cuenta_bancaria_tercero',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'id_tercero', label: 'Id tercero' },
      { key: 'banco', label: 'Banco' },
      { key: 'tipo_cuenta', label: 'Tipo cuenta' },
      { key: 'numero_cuenta', label: 'Numero cuenta' },
      { key: 'activa', label: 'Activa', type: 'boolean' },
    ],
    formFields: [
      { key: 'id_tercero', label: 'Id tercero', type: 'text', required: true },
      { key: 'banco', label: 'Banco', type: 'text', required: true },
      { key: 'tipo_cuenta', label: 'Tipo cuenta', type: 'text', required: true },
      { key: 'numero_cuenta', label: 'Numero cuenta', type: 'text', required: true },
      { key: 'titular', label: 'Titular', type: 'text', required: true },
      { key: 'moneda', label: 'Moneda', type: 'text' },
      { key: 'es_principal', label: 'Es principal', type: 'checkbox' },
      { key: 'activa', label: 'Activa', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/third-party-documents': {
    key: 'third-party-documents',
    domain: 'masters',
    title: 'Documentos de terceros',
    subtitle: 'Soportes legales y comerciales asociados a terceros.',
    endpoint: '/masters/third-party-documents',
    idKey: 'id_documento_tercero',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'id_tercero', label: 'Id tercero' },
      { key: 'tipo_documento', label: 'Tipo documento' },
      { key: 'nombre_documento', label: 'Nombre documento' },
      { key: 'fecha_vencimiento', label: 'Vencimiento', type: 'date' },
      { key: 'vigente', label: 'Vigente', type: 'boolean' },
    ],
    formFields: [
      { key: 'id_tercero', label: 'Id tercero', type: 'text', required: true },
      { key: 'tipo_documento', label: 'Tipo documento', type: 'text', required: true },
      { key: 'nombre_documento', label: 'Nombre documento', type: 'text', required: true },
      { key: 'numero_documento', label: 'Numero documento', type: 'text' },
      { key: 'fecha_emision', label: 'Fecha emision', type: 'date' },
      { key: 'fecha_vencimiento', label: 'Fecha vencimiento', type: 'date' },
      { key: 'url_archivo', label: 'URL archivo', type: 'text' },
      { key: 'hash_archivo', label: 'Hash archivo', type: 'text' },
      { key: 'version', label: 'Version', type: 'text' },
      { key: 'vigente', label: 'Vigente', type: 'checkbox', defaultValue: true },
      { key: 'observaciones', label: 'Observaciones', type: 'textarea', rows: 3 },
    ],
  },
  'masters/product-tags': {
    key: 'product-tags',
    domain: 'masters',
    title: 'Etiquetas de producto',
    subtitle: 'Etiquetas comerciales y operativas para catalogo y busqueda.',
    endpoint: '/masters/product-tags',
    idKey: 'id_etiqueta_producto',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Codigo' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'descripcion', label: 'Descripcion' },
      { key: 'activa', label: 'Activa', type: 'boolean' },
    ],
    formFields: [
      { key: 'codigo', label: 'Codigo', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'descripcion', label: 'Descripcion', type: 'textarea', rows: 3 },
      { key: 'activa', label: 'Activa', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/product-tag-links': {
    key: 'product-tag-links',
    domain: 'masters',
    title: 'Relacion producto-etiqueta',
    subtitle: 'Vinculos entre productos y etiquetas para catalogacion.',
    endpoint: '/masters/product-tag-links',
    idKey: 'id_producto_etiqueta',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'id_producto', label: 'Id producto' },
      { key: 'id_etiqueta_producto', label: 'Id etiqueta' },
    ],
    formFields: [
      { key: 'id_producto', label: 'Id producto', type: 'text', required: true },
      { key: 'id_etiqueta_producto', label: 'Id etiqueta producto', type: 'text', required: true },
    ],
  },
  'masters/product-packages': {
    key: 'product-packages',
    domain: 'masters',
    title: 'Embalajes de producto',
    subtitle: 'Presentaciones de venta, compra y logistica por producto.',
    endpoint: '/masters/product-packages',
    idKey: 'id_producto_embalaje',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'id_producto', label: 'Id producto' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'tipo_embalaje', label: 'Tipo embalaje' },
      { key: 'cantidad_unidades_base', label: 'Cant. base' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'id_producto', label: 'Id producto', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'tipo_embalaje', label: 'Tipo embalaje', type: 'text', required: true },
      { key: 'cantidad_unidades_base', label: 'Cantidad unidades base', type: 'number', required: true },
      { key: 'id_unidad_medida', label: 'Id unidad medida', type: 'text', required: true },
      { key: 'peso', label: 'Peso', type: 'number' },
      { key: 'alto', label: 'Alto', type: 'number' },
      { key: 'ancho', label: 'Ancho', type: 'number' },
      { key: 'largo', label: 'Largo', type: 'number' },
      { key: 'codigo_barras', label: 'Codigo barras', type: 'text' },
      { key: 'es_venta', label: 'Es venta', type: 'checkbox' },
      { key: 'es_compra', label: 'Es compra', type: 'checkbox' },
      { key: 'es_logistico', label: 'Es logistico', type: 'checkbox' },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/product-components': {
    key: 'product-components',
    domain: 'masters',
    title: 'Componentes de producto',
    subtitle: 'Relacion de kits, combos y componentes obligatorios.',
    endpoint: '/masters/product-components',
    idKey: 'id_producto_componente',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'id_producto_padre', label: 'Producto padre' },
      { key: 'id_producto_hijo', label: 'Producto hijo' },
      { key: 'cantidad', label: 'Cantidad' },
      { key: 'obligatorio', label: 'Obligatorio', type: 'boolean' },
    ],
    formFields: [
      { key: 'id_producto_padre', label: 'Id producto padre', type: 'text', required: true },
      { key: 'id_producto_hijo', label: 'Id producto hijo', type: 'text', required: true },
      { key: 'cantidad', label: 'Cantidad', type: 'number', required: true },
      { key: 'obligatorio', label: 'Obligatorio', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/product-taxes': {
    key: 'product-taxes',
    domain: 'masters',
    title: 'Impuestos por producto',
    subtitle: 'Asignacion tributaria de productos por tasa y vigencia.',
    endpoint: '/masters/product-taxes',
    idKey: 'id_producto_impuesto',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'id_producto', label: 'Id producto' },
      { key: 'id_tasa_impuesto', label: 'Id tasa' },
      { key: 'tipo_aplicacion', label: 'Tipo aplicacion' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'id_producto', label: 'Id producto', type: 'text', required: true },
      { key: 'id_tasa_impuesto', label: 'Id tasa impuesto', type: 'text', required: true },
      { key: 'tipo_aplicacion', label: 'Tipo aplicacion', type: 'text', required: true },
      { key: 'fecha_inicio_vigencia', label: 'Inicio vigencia', type: 'date', required: true },
      { key: 'fecha_fin_vigencia', label: 'Fin vigencia', type: 'date' },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/product-documents': {
    key: 'product-documents',
    domain: 'masters',
    title: 'Documentos de producto',
    subtitle: 'Soportes tecnicos, regulatorios y comerciales por producto.',
    endpoint: '/masters/product-documents',
    idKey: 'id_producto_documento',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'id_producto', label: 'Id producto' },
      { key: 'tipo_documento', label: 'Tipo documento' },
      { key: 'nombre_documento', label: 'Nombre documento' },
      { key: 'fecha_vencimiento', label: 'Vencimiento', type: 'date' },
      { key: 'vigente', label: 'Vigente', type: 'boolean' },
    ],
    formFields: [
      { key: 'id_producto', label: 'Id producto', type: 'text', required: true },
      { key: 'tipo_documento', label: 'Tipo documento', type: 'text', required: true },
      { key: 'nombre_documento', label: 'Nombre documento', type: 'text', required: true },
      { key: 'numero_documento', label: 'Numero documento', type: 'text' },
      { key: 'fecha_emision', label: 'Fecha emision', type: 'date' },
      { key: 'fecha_vencimiento', label: 'Fecha vencimiento', type: 'date' },
      { key: 'entidad_emisora', label: 'Entidad emisora', type: 'text' },
      { key: 'url_archivo', label: 'URL archivo', type: 'text' },
      { key: 'hash_archivo', label: 'Hash archivo', type: 'text' },
      { key: 'version', label: 'Version', type: 'text' },
      { key: 'vigente', label: 'Vigente', type: 'checkbox', defaultValue: true },
      { key: 'observaciones', label: 'Observaciones', type: 'textarea', rows: 3 },
    ],
  },
  'masters/sanitary-records': {
    key: 'sanitary-records',
    domain: 'masters',
    title: 'Registros sanitarios',
    subtitle: 'Control regulatorio y vigencia sanitaria por producto.',
    endpoint: '/masters/sanitary-records',
    idKey: 'id_registro_sanitario_producto',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'id_producto', label: 'Id producto' },
      { key: 'entidad_reguladora', label: 'Entidad reguladora' },
      { key: 'numero_registro', label: 'Numero registro' },
      { key: 'fecha_vencimiento', label: 'Vencimiento', type: 'date' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'id_producto', label: 'Id producto', type: 'text', required: true },
      { key: 'entidad_reguladora', label: 'Entidad reguladora', type: 'text', required: true },
      { key: 'tipo_registro', label: 'Tipo registro', type: 'text', required: true },
      { key: 'numero_registro', label: 'Numero registro', type: 'text', required: true },
      { key: 'fecha_emision', label: 'Fecha emision', type: 'date' },
      { key: 'fecha_vencimiento', label: 'Fecha vencimiento', type: 'date' },
      { key: 'estado_registro', label: 'Estado registro', type: 'text' },
      { key: 'titular_registro', label: 'Titular registro', type: 'text' },
      { key: 'url_soporte', label: 'URL soporte', type: 'text' },
      { key: 'observaciones', label: 'Observaciones', type: 'textarea', rows: 3 },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/sales-channels': {
    key: 'sales-channels',
    domain: 'masters',
    title: 'Canales de venta',
    subtitle: 'Canales comerciales habilitados para listas y pedidos.',
    endpoint: '/masters/sales-channels',
    idKey: 'id_canal_venta',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Codigo' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'tipo_canal', label: 'Tipo canal' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'codigo', label: 'Codigo', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'tipo_canal', label: 'Tipo canal', type: 'text', required: true },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/price-lists': {
    key: 'price-lists',
    domain: 'masters',
    title: 'Listas de precios',
    subtitle: 'Listas de precio por moneda, canal y vigencia.',
    endpoint: '/masters/price-lists',
    idKey: 'id_lista_precio',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Codigo' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'id_moneda', label: 'Id moneda' },
      { key: 'id_canal_venta', label: 'Id canal venta' },
      { key: 'activa', label: 'Activa', type: 'boolean' },
    ],
    formFields: [
      { key: 'codigo', label: 'Codigo', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'id_moneda', label: 'Id moneda', type: 'text', required: true },
      { key: 'id_canal_venta', label: 'Id canal venta', type: 'text', required: true },
      { key: 'descripcion', label: 'Descripcion', type: 'textarea', rows: 3 },
      { key: 'fecha_inicio_vigencia', label: 'Inicio vigencia', type: 'date', required: true },
      { key: 'fecha_fin_vigencia', label: 'Fin vigencia', type: 'date' },
      { key: 'activa', label: 'Activa', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/product-prices': {
    key: 'product-prices',
    domain: 'masters',
    title: 'Precios de producto',
    subtitle: 'Precios vigentes por lista, producto y margen objetivo.',
    endpoint: '/masters/product-prices',
    idKey: 'id_precio_producto',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'id_producto', label: 'Id producto' },
      { key: 'id_lista_precio', label: 'Id lista precio' },
      { key: 'precio_base', label: 'Precio base' },
      { key: 'fecha_inicio_vigencia', label: 'Inicio', type: 'date' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'id_producto', label: 'Id producto', type: 'text', required: true },
      { key: 'id_lista_precio', label: 'Id lista precio', type: 'text', required: true },
      { key: 'precio_base', label: 'Precio base', type: 'number', required: true },
      { key: 'costo_referencia', label: 'Costo referencia', type: 'number' },
      { key: 'margen_objetivo_pct', label: 'Margen objetivo %', type: 'number' },
      { key: 'precio_minimo', label: 'Precio minimo', type: 'number' },
      { key: 'precio_maximo', label: 'Precio maximo', type: 'number' },
      { key: 'incluye_impuestos', label: 'Incluye impuestos', type: 'checkbox', defaultValue: true },
      { key: 'fecha_inicio_vigencia', label: 'Inicio vigencia', type: 'date', required: true },
      { key: 'fecha_fin_vigencia', label: 'Fin vigencia', type: 'date' },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'inventory/branches': {
    key: 'branches',
    domain: 'inventory',
    title: 'Sucursales',
    subtitle: 'Puntos de operación y administración comercial.',
    endpoint: '/inventory/branches',
    idKey: 'id_sucursal',
    permission: 'inventory.manage',
    badge: 'Inventario',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'telefono', label: 'Teléfono' },
      { key: 'correo_electronico', label: 'Correo' },
      { key: 'activa', label: 'Activa', type: 'boolean' },
    ],
    formFields: [
      { key: 'codigo', label: 'Código', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'telefono', label: 'Teléfono', type: 'text' },
      { key: 'correo_electronico', label: 'Correo', type: 'email' },
      { key: 'activa', label: 'Activa', type: 'checkbox', defaultValue: true },
    ],
  },
  'inventory/warehouses': {
    key: 'warehouses',
    domain: 'inventory',
    title: 'Bodegas',
    subtitle: 'Control logístico por bodega, reglas de operación y permisos.',
    endpoint: '/inventory/warehouses',
    idKey: 'id_bodega',
    permission: 'inventory.manage',
    badge: 'Inventario',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'tipo_bodega', label: 'Tipo' },
      { key: 'permite_ventas', label: 'Ventas', type: 'boolean' },
      { key: 'activa', label: 'Activa', type: 'boolean' },
    ],
    formFields: [
      { key: 'id_sucursal', label: 'Id sucursal', type: 'text', required: true },
      { key: 'codigo', label: 'Código', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'tipo_bodega', label: 'Tipo bodega', type: 'text', required: true },
      { key: 'direccion', label: 'Dirección', type: 'textarea', rows: 3 },
      { key: 'permite_ventas', label: 'Permite ventas', type: 'checkbox' },
      { key: 'permite_compras', label: 'Permite compras', type: 'checkbox' },
      { key: 'permite_traslados', label: 'Permite traslados', type: 'checkbox' },
      { key: 'activa', label: 'Activa', type: 'checkbox', defaultValue: true },
    ],
  },
  'inventory/locations': {
    key: 'locations',
    domain: 'inventory',
    title: 'Ubicaciones',
    subtitle: 'Mapa físico de almacenamiento por bodega y zona.',
    endpoint: '/inventory/locations',
    idKey: 'id_ubicacion',
    permission: 'inventory.manage',
    badge: 'Inventario',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'pasillo', label: 'Pasillo' },
      { key: 'estante', label: 'Estante' },
      { key: 'bloqueada', label: 'Bloqueada', type: 'boolean' },
      { key: 'activa', label: 'Activa', type: 'boolean' },
    ],
    formFields: [
      { key: 'id_bodega', label: 'Id bodega', type: 'text', required: true },
      { key: 'codigo', label: 'Código', type: 'text', required: true },
      { key: 'pasillo', label: 'Pasillo', type: 'text' },
      { key: 'estante', label: 'Estante', type: 'text' },
      { key: 'nivel', label: 'Nivel', type: 'text' },
      { key: 'posicion', label: 'Posición', type: 'text' },
      { key: 'bloqueada', label: 'Bloqueada', type: 'checkbox' },
      { key: 'activa', label: 'Activa', type: 'checkbox', defaultValue: true },
    ],
  },
  'inventory/lots': {
    key: 'lots',
    domain: 'inventory',
    title: 'Lotes',
    subtitle: 'Trazabilidad por lote, estado y vencimiento.',
    endpoint: '/inventory/lots',
    idKey: 'id_lote_producto',
    permission: 'inventory.manage',
    badge: 'Inventario',
    createMode: 'guided',
    columns: [
      { key: 'numero_lote', label: 'Lote' },
      { key: 'estado_lote', label: 'Estado' },
      { key: 'fecha_vencimiento', label: 'Vencimiento', type: 'date' },
      { key: 'observaciones', label: 'Observaciones' },
    ],
    formFields: [
      { key: 'id_producto', label: 'Id producto', type: 'text', required: true },
      { key: 'numero_lote', label: 'Número de lote', type: 'text', required: true },
      { key: 'fecha_fabricacion', label: 'Fabricación', type: 'date' },
      { key: 'fecha_vencimiento', label: 'Vencimiento', type: 'date' },
      { key: 'estado_lote', label: 'Estado', type: 'text', required: true },
      { key: 'observaciones', label: 'Observaciones', type: 'textarea', rows: 3 },
    ],
  },
  'purchases/payment-terms': {
    key: 'payment-terms',
    domain: 'purchases',
    title: 'Condiciones de pago',
    subtitle: 'Parámetros comerciales de compras y facturas de proveedor.',
    endpoint: '/purchases/payment-terms',
    idKey: 'id_condicion_pago',
    permission: 'purchases.manage',
    badge: 'Compras',
    createMode: 'json',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'dias_credito', label: 'Días crédito' },
      { key: 'activa', label: 'Activa', type: 'boolean' },
    ],
  },
  'sales/clients': {
    key: 'clients',
    domain: 'sales',
    title: 'Clientes',
    subtitle: 'Base comercial y omnicanal de clientes.',
    endpoint: '/sales/clients',
    idKey: 'id_cliente',
    permission: 'sales.manage',
    badge: 'Ventas',
    createMode: 'guided',
    columns: [
      { key: 'codigo_cliente', label: 'Código' },
      { key: 'correo_electronico', label: 'Correo' },
      { key: 'telefono', label: 'Teléfono' },
      { key: 'acepta_marketing', label: 'Marketing', type: 'boolean' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'codigo_cliente', label: 'Código cliente', type: 'text', required: true },
      { key: 'id_tercero', label: 'Id tercero', type: 'text' },
      { key: 'correo_electronico', label: 'Correo', type: 'email' },
      { key: 'telefono', label: 'Teléfono', type: 'text' },
      { key: 'acepta_marketing', label: 'Acepta marketing', type: 'checkbox' },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'sales/payment-methods': {
    key: 'payment-methods',
    domain: 'sales',
    title: 'Medios de pago',
    subtitle: 'Configuración de recaudo y conciliación.',
    endpoint: '/sales/payment-methods',
    idKey: 'id_metodo_pago',
    permission: 'sales.manage',
    badge: 'Ventas',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'tipo_metodo', label: 'Tipo' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'codigo', label: 'Código', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'tipo_metodo', label: 'Tipo método', type: 'text', required: true },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'compliance/privacy-policies': {
    key: 'privacy-policies',
    domain: 'compliance',
    title: 'Políticas de privacidad',
    subtitle: 'Versionado y vigencia de políticas.',
    endpoint: '/compliance/privacy-policies',
    idKey: 'id_politica_privacidad',
    permission: 'compliance.manage',
    badge: 'Cumplimiento',
    createMode: 'guided',
    columns: [
      { key: 'version', label: 'Versión' },
      { key: 'fecha_inicio_vigencia', label: 'Inicio', type: 'date' },
      { key: 'fecha_fin_vigencia', label: 'Fin', type: 'date' },
      { key: 'activa', label: 'Activa', type: 'boolean' },
    ],
    formFields: [
      { key: 'version', label: 'Versión', type: 'text', required: true },
      { key: 'fecha_inicio_vigencia', label: 'Inicio vigencia', type: 'date', required: true },
      { key: 'fecha_fin_vigencia', label: 'Fin vigencia', type: 'date' },
      { key: 'contenido', label: 'Contenido', type: 'textarea', rows: 6, required: true },
      { key: 'activa', label: 'Activa', type: 'checkbox', defaultValue: true },
    ],
  },
  'audit/approval-flows': {
    key: 'approval-flows',
    domain: 'audit',
    title: 'Flujos de aprobación',
    subtitle: 'Gobierno de aprobaciones y niveles de validación.',
    endpoint: '/audit/approval-flows',
    idKey: 'id_flujo_aprobacion',
    permission: 'audit.read',
    badge: 'Auditoría',
    createMode: 'json',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'estado', label: 'Estado', type: 'badge' },
    ],
  },
  'integrations/systems': {
    key: 'systems',
    domain: 'integrations',
    title: 'Sistemas externos',
    subtitle: 'Inventario de integraciones empresariales y conectores.',
    endpoint: '/integrations/systems',
    idKey: 'id_sistema_integracion',
    permission: 'reports.read',
    badge: 'Integraciones',
    createMode: 'json',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'tipo_sistema', label: 'Tipo' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
  },
};

export const ENTITY_OPTIONS = Object.values(ENTITY_REGISTRY);

export function getEntityConfig(domain: string, entity: string) {
  return ENTITY_REGISTRY[`${domain}/${entity}`];
}
