import { EntityConfig } from '../models/app.models';

export const ENTITY_REGISTRY: Record<string, EntityConfig> = {
  'security/users': {
    key: 'users',
    domain: 'security',
    title: 'Usuarios',
    subtitle: 'Administración de cuentas, credenciales y acceso operativo.',
    endpoint: '/security/users',
    idKey: 'id_usuario',
    permission: 'security.manage',
    badge: 'Seguridad',
    createMode: 'guided',
    columns: [
      { key: 'nombre_usuario', label: 'Usuario' },
      { key: 'correo_electronico', label: 'Correo' },
      { key: 'nombres', label: 'Nombres' },
      { key: 'apellidos', label: 'Apellidos' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'nombres', label: 'Nombres', type: 'text', required: true },
      { key: 'apellidos', label: 'Apellidos', type: 'text', required: true },
      { key: 'correo_electronico', label: 'Correo', type: 'email', required: true },
      { key: 'telefono', label: 'Teléfono', type: 'text' },
      { key: 'nombre_usuario', label: 'Usuario', type: 'text', required: true },
      { key: 'password', label: 'Contraseña inicial', type: 'password', required: true },
      {
        key: 'requiere_cambio_clave',
        label: 'Exigir cambio de clave',
        type: 'checkbox',
        defaultValue: true,
      },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'security/roles': {
    key: 'roles',
    domain: 'security',
    title: 'Roles',
    subtitle: 'Perfiles funcionales y agrupación de permisos.',
    endpoint: '/security/roles',
    idKey: 'id_rol',
    permission: 'security.manage',
    badge: 'Seguridad',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'descripcion', label: 'Descripción' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'codigo', label: 'Código', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'descripcion', label: 'Descripción', type: 'textarea', rows: 3 },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'security/permissions': {
    key: 'permissions',
    domain: 'security',
    title: 'Permisos',
    subtitle: 'Permisos funcionales vinculados a módulos y acciones.',
    endpoint: '/security/permissions',
    idKey: 'id_permiso',
    permission: 'security.manage',
    badge: 'Seguridad',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'modulo', label: 'Módulo' },
      { key: 'accion', label: 'Acción' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'modulo', label: 'Módulo', type: 'text', required: true },
      { key: 'codigo', label: 'Código', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'descripcion', label: 'Descripción', type: 'textarea', rows: 3 },
      { key: 'accion', label: 'Acción', type: 'text', required: true },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/categories': {
    key: 'categories',
    domain: 'masters',
    title: 'Categorías',
    subtitle: 'Jerarquía comercial y regulatoria de productos.',
    endpoint: '/masters/categories',
    idKey: 'id_categoria_producto',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'nivel', label: 'Nivel' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'codigo', label: 'Código', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'descripcion', label: 'Descripción', type: 'textarea', rows: 3 },
      { key: 'nivel', label: 'Nivel', type: 'number', defaultValue: 1 },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/brands': {
    key: 'brands',
    domain: 'masters',
    title: 'Marcas',
    subtitle: 'Fabricantes y marcas comerciales.',
    endpoint: '/masters/brands',
    idKey: 'id_marca',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'descripcion', label: 'Descripción' },
      { key: 'activa', label: 'Activa', type: 'boolean' },
    ],
    formFields: [
      { key: 'codigo', label: 'Código', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'descripcion', label: 'Descripción', type: 'textarea', rows: 3 },
      { key: 'activa', label: 'Activa', type: 'checkbox', defaultValue: true },
    ],
  },
  'masters/products': {
    key: 'products',
    domain: 'masters',
    title: 'Productos',
    subtitle: 'Ficha maestra de referencias, control sanitario y reglas de stock.',
    endpoint: '/masters/products',
    idKey: 'id_producto',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'sku', label: 'SKU' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'tipo_producto', label: 'Tipo' },
      { key: 'stock_minimo', label: 'Stock mínimo' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'sku', label: 'SKU', type: 'text', required: true },
      { key: 'codigo_barras', label: 'Código de barras', type: 'text' },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'nombre_corto', label: 'Nombre corto', type: 'text' },
      { key: 'descripcion', label: 'Descripción', type: 'textarea', rows: 4 },
      { key: 'tipo_producto', label: 'Tipo de producto', type: 'text', required: true },
      { key: 'subtipo_producto', label: 'Subtipo', type: 'text' },
      { key: 'stock_minimo', label: 'Stock mínimo', type: 'number' },
      { key: 'stock_maximo', label: 'Stock máximo', type: 'number' },
      { key: 'punto_reorden', label: 'Punto de reorden', type: 'number' },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
      { key: 'es_inventariable', label: 'Inventariable', type: 'checkbox', defaultValue: true },
      { key: 'maneja_lotes', label: 'Maneja lotes', type: 'checkbox' },
      { key: 'maneja_vencimiento', label: 'Maneja vencimiento', type: 'checkbox' },
      {
        key: 'requiere_registro_sanitario',
        label: 'Requiere registro sanitario',
        type: 'checkbox',
      },
      {
        key: 'requiere_control_mayoria_edad',
        label: 'Control mayoría de edad',
        type: 'checkbox',
      },
    ],
  },
  'masters/third-parties': {
    key: 'third-parties',
    domain: 'masters',
    title: 'Terceros',
    subtitle: 'Proveedores, clientes, fabricantes y demás contrapartes.',
    endpoint: '/masters/third-parties',
    idKey: 'id_tercero',
    permission: 'masters.manage',
    badge: 'Maestros',
    createMode: 'guided',
    columns: [
      { key: 'tipo_tercero', label: 'Tipo' },
      { key: 'numero_documento', label: 'Documento' },
      { key: 'razon_social', label: 'Razón social' },
      { key: 'correo_electronico', label: 'Correo' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'tipo_tercero', label: 'Tipo de tercero', type: 'text', required: true },
      { key: 'tipo_persona', label: 'Tipo de persona', type: 'text', required: true },
      { key: 'numero_documento', label: 'Documento', type: 'text', required: true },
      { key: 'razon_social', label: 'Razón social', type: 'text' },
      { key: 'nombres', label: 'Nombres', type: 'text' },
      { key: 'apellidos', label: 'Apellidos', type: 'text' },
      { key: 'nombre_comercial', label: 'Nombre comercial', type: 'text' },
      { key: 'correo_electronico', label: 'Correo', type: 'email' },
      { key: 'telefono_principal', label: 'Teléfono', type: 'text' },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'inventory/branches': {
    key: 'branches',
    domain: 'inventory',
    title: 'Sucursales',
    subtitle: 'Puntos de operación y administración comercial.',
    endpoint: '/inventory/branches',
    idKey: 'id_sucursal',
    permission: 'inventory.manage',
    badge: 'Inventario',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'telefono', label: 'Teléfono' },
      { key: 'correo_electronico', label: 'Correo' },
      { key: 'activa', label: 'Activa', type: 'boolean' },
    ],
    formFields: [
      { key: 'codigo', label: 'Código', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'telefono', label: 'Teléfono', type: 'text' },
      { key: 'correo_electronico', label: 'Correo', type: 'email' },
      { key: 'activa', label: 'Activa', type: 'checkbox', defaultValue: true },
    ],
  },
  'inventory/warehouses': {
    key: 'warehouses',
    domain: 'inventory',
    title: 'Bodegas',
    subtitle: 'Control logístico por bodega, reglas de operación y permisos.',
    endpoint: '/inventory/warehouses',
    idKey: 'id_bodega',
    permission: 'inventory.manage',
    badge: 'Inventario',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'tipo_bodega', label: 'Tipo' },
      { key: 'permite_ventas', label: 'Ventas', type: 'boolean' },
      { key: 'activa', label: 'Activa', type: 'boolean' },
    ],
    formFields: [
      { key: 'id_sucursal', label: 'Id sucursal', type: 'text', required: true },
      { key: 'codigo', label: 'Código', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'tipo_bodega', label: 'Tipo bodega', type: 'text', required: true },
      { key: 'direccion', label: 'Dirección', type: 'textarea', rows: 3 },
      { key: 'permite_ventas', label: 'Permite ventas', type: 'checkbox' },
      { key: 'permite_compras', label: 'Permite compras', type: 'checkbox' },
      { key: 'permite_traslados', label: 'Permite traslados', type: 'checkbox' },
      { key: 'activa', label: 'Activa', type: 'checkbox', defaultValue: true },
    ],
  },
  'inventory/locations': {
    key: 'locations',
    domain: 'inventory',
    title: 'Ubicaciones',
    subtitle: 'Mapa físico de almacenamiento por bodega y zona.',
    endpoint: '/inventory/locations',
    idKey: 'id_ubicacion',
    permission: 'inventory.manage',
    badge: 'Inventario',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'pasillo', label: 'Pasillo' },
      { key: 'estante', label: 'Estante' },
      { key: 'bloqueada', label: 'Bloqueada', type: 'boolean' },
      { key: 'activa', label: 'Activa', type: 'boolean' },
    ],
    formFields: [
      { key: 'id_bodega', label: 'Id bodega', type: 'text', required: true },
      { key: 'codigo', label: 'Código', type: 'text', required: true },
      { key: 'pasillo', label: 'Pasillo', type: 'text' },
      { key: 'estante', label: 'Estante', type: 'text' },
      { key: 'nivel', label: 'Nivel', type: 'text' },
      { key: 'posicion', label: 'Posición', type: 'text' },
      { key: 'bloqueada', label: 'Bloqueada', type: 'checkbox' },
      { key: 'activa', label: 'Activa', type: 'checkbox', defaultValue: true },
    ],
  },
  'inventory/lots': {
    key: 'lots',
    domain: 'inventory',
    title: 'Lotes',
    subtitle: 'Trazabilidad por lote, estado y vencimiento.',
    endpoint: '/inventory/lots',
    idKey: 'id_lote_producto',
    permission: 'inventory.manage',
    badge: 'Inventario',
    createMode: 'guided',
    columns: [
      { key: 'numero_lote', label: 'Lote' },
      { key: 'estado_lote', label: 'Estado' },
      { key: 'fecha_vencimiento', label: 'Vencimiento', type: 'date' },
      { key: 'observaciones', label: 'Observaciones' },
    ],
    formFields: [
      { key: 'id_producto', label: 'Id producto', type: 'text', required: true },
      { key: 'numero_lote', label: 'Número de lote', type: 'text', required: true },
      { key: 'fecha_fabricacion', label: 'Fabricación', type: 'date' },
      { key: 'fecha_vencimiento', label: 'Vencimiento', type: 'date' },
      { key: 'estado_lote', label: 'Estado', type: 'text', required: true },
      { key: 'observaciones', label: 'Observaciones', type: 'textarea', rows: 3 },
    ],
  },
  'purchases/payment-terms': {
    key: 'payment-terms',
    domain: 'purchases',
    title: 'Condiciones de pago',
    subtitle: 'Parámetros comerciales de compras y facturas de proveedor.',
    endpoint: '/purchases/payment-terms',
    idKey: 'id_condicion_pago',
    permission: 'purchases.manage',
    badge: 'Compras',
    createMode: 'json',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'dias_credito', label: 'Días crédito' },
      { key: 'activa', label: 'Activa', type: 'boolean' },
    ],
  },
  'sales/clients': {
    key: 'clients',
    domain: 'sales',
    title: 'Clientes',
    subtitle: 'Base comercial y omnicanal de clientes.',
    endpoint: '/sales/clients',
    idKey: 'id_cliente',
    permission: 'sales.manage',
    badge: 'Ventas',
    createMode: 'guided',
    columns: [
      { key: 'codigo_cliente', label: 'Código' },
      { key: 'correo_electronico', label: 'Correo' },
      { key: 'telefono', label: 'Teléfono' },
      { key: 'acepta_marketing', label: 'Marketing', type: 'boolean' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'codigo_cliente', label: 'Código cliente', type: 'text', required: true },
      { key: 'id_tercero', label: 'Id tercero', type: 'text' },
      { key: 'correo_electronico', label: 'Correo', type: 'email' },
      { key: 'telefono', label: 'Teléfono', type: 'text' },
      { key: 'acepta_marketing', label: 'Acepta marketing', type: 'checkbox' },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'sales/payment-methods': {
    key: 'payment-methods',
    domain: 'sales',
    title: 'Medios de pago',
    subtitle: 'Configuración de recaudo y conciliación.',
    endpoint: '/sales/payment-methods',
    idKey: 'id_metodo_pago',
    permission: 'sales.manage',
    badge: 'Ventas',
    createMode: 'guided',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'tipo_metodo', label: 'Tipo' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
    formFields: [
      { key: 'codigo', label: 'Código', type: 'text', required: true },
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'tipo_metodo', label: 'Tipo método', type: 'text', required: true },
      { key: 'activo', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  'compliance/privacy-policies': {
    key: 'privacy-policies',
    domain: 'compliance',
    title: 'Políticas de privacidad',
    subtitle: 'Versionado y vigencia de políticas.',
    endpoint: '/compliance/privacy-policies',
    idKey: 'id_politica_privacidad',
    permission: 'compliance.manage',
    badge: 'Cumplimiento',
    createMode: 'guided',
    columns: [
      { key: 'version', label: 'Versión' },
      { key: 'fecha_inicio_vigencia', label: 'Inicio', type: 'date' },
      { key: 'fecha_fin_vigencia', label: 'Fin', type: 'date' },
      { key: 'activa', label: 'Activa', type: 'boolean' },
    ],
    formFields: [
      { key: 'version', label: 'Versión', type: 'text', required: true },
      { key: 'fecha_inicio_vigencia', label: 'Inicio vigencia', type: 'date', required: true },
      { key: 'fecha_fin_vigencia', label: 'Fin vigencia', type: 'date' },
      { key: 'contenido', label: 'Contenido', type: 'textarea', rows: 6, required: true },
      { key: 'activa', label: 'Activa', type: 'checkbox', defaultValue: true },
    ],
  },
  'audit/approval-flows': {
    key: 'approval-flows',
    domain: 'audit',
    title: 'Flujos de aprobación',
    subtitle: 'Gobierno de aprobaciones y niveles de validación.',
    endpoint: '/audit/approval-flows',
    idKey: 'id_flujo_aprobacion',
    permission: 'audit.read',
    badge: 'Auditoría',
    createMode: 'json',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'estado', label: 'Estado', type: 'badge' },
    ],
  },
  'integrations/systems': {
    key: 'systems',
    domain: 'integrations',
    title: 'Sistemas externos',
    subtitle: 'Inventario de integraciones empresariales y conectores.',
    endpoint: '/integrations/systems',
    idKey: 'id_sistema_integracion',
    permission: 'reports.read',
    badge: 'Integraciones',
    createMode: 'json',
    columns: [
      { key: 'codigo', label: 'Código' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'tipo_sistema', label: 'Tipo' },
      { key: 'activo', label: 'Activo', type: 'boolean' },
    ],
  },
};

export const ENTITY_OPTIONS = Object.values(ENTITY_REGISTRY);

export function getEntityConfig(domain: string, entity: string) {
  return ENTITY_REGISTRY[`${domain}/${entity}`];
}
